static wil::com_ptr<ICoreWebView2Controller> wv_controller;
static wil::com_ptr<ICoreWebView2> wv;
static wil::com_ptr<ICoreWebView2Settings> wv_settings;
LRESULT CALLBACK WndProc(HWND hwnd, UINT umsg, WPARAM wparam, LPARAM lparam);
int APIENTRY wWinMain(HINSTANCE histance, HINSTANCE hprevinstance, PWSTR pcmdline, int ncmdshow);
int lightMode;
int ModeCheck();
void DarkTitle();
void DarkMode(HWND hwnd);
void SetMica(HWND hwnd);
void ExtendFrame(HWND hwnd);
void KeyTop(HWND hwnd);
void KeyMaximize(HWND hwnd);
void KeyFullscreen(HWND hwnd);
void WebViewNavigate(wil::com_ptr<ICoreWebView2> wv);
