#pragma once
#include <dwmapi.h>
#include <WebView2.h>
#include <wil/com.h>
#include <wil/cppwinrt.h>
#include <wrl.h>
#include <winrt/Windows.Foundation.h>
#include <winrt/Windows.UI.ViewManagement.h>
#include <gdiplus.h>
#include <ShlObj.h>
#include <locale>
#include <codecvt>
#include <string>
#include <filesystem>
#include <fstream>
#include <json.hpp>
