#define PROGRAM_ICON 1

#define IDR_MAINFRAME 128
#define IDD_WINDOWSPROJECT1_DIALOG 102
#define IDD_ABOUTBOX 103
#define IDM_ABOUT 104
#define IDM_EXIT 105
#define IDI_WINDOWSPROJECT1 107
#define IDI_SMALL 108
#define IDC_WINDOWSPROJECT1 109
#define IDC_MYICON 2

#ifndef IDC_STATIC
#define IDC_STATIC -1
#endif
