name: Airglow

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: true
          path: airglow

      - name: Checkout website
        uses: actions/checkout@v4
        with:
          repository: mthierman/mthierman.com
          token: ${{ secrets.WEBSITE }}
          path: mthierman.com

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "*"
          check-latest: true
          cache: "pnpm"
          cache-dependency-path: airglow/pnpm-lock.yaml

      - name: Install node_modules
        run: |
          Set-Location ${{ github.workspace }}\airglow
          pnpm install

      - name: Cache
        uses: actions/cache@v4
        id: deps
        with:
          path: |
            ${{ github.workspace }}/airglow/build/_deps
          key: deps-${{ hashFiles('airglow/CMakeLists.txt') }}

      - name: Stable release
        if: github.ref == 'refs/heads/main'
        run: |
          Set-Location ${{ github.workspace }}\airglow
          Import-Module ${{ github.workspace }}\airglow\libs\Glow\tools\PowerShell
          Import-Module ${{ github.workspace }}\airglow\tools\PowerShell
          Invoke-DevShell
          Invoke-CMake
          Compress-Airglow
          Restore-Wix
          Build-AirglowInstaller
          Publish-Airglow

      - name: Update website
        run: |
          Set-Location ${{ github.workspace }}\mthierman.com
          Copy-Item "${{ github.workspace }}\airglow\build\notes\version" -Destination "${{ github.workspace }}\mthierman.com\src\includes\airglow\version"
          Get-Date -Format "dd/MM/yyyy HH:mm:ss" > "${{ github.workspace }}\mthierman.com\src\includes\airglow\date"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A
          git commit -m 'Update Airglow'
          git push
