name: Gooey Release

on:
  workflow_dispatch:
  push:
    branches: [main, dev]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: nuget-cache
        with:
          path: external
          key: nuget-cache-${{ hashFiles('**/CMakeLists.txt') }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cmake --preset deploy
          cmake --build --preset deploy
          (Get-Date | Out-String).trim() > build/Release/date.txt
          git --no-pager log -5 --oneline --no-decorate > build/Release/changes.txt

          $version = Get-Content "build/Release/version.txt"
          $date = Get-Content "build/Release/date.txt"
          $changes = Get-Item "build/Release/changes.txt"
          $exe = Get-Item "build/Release/Gooey.exe"

          if ("${{ github.ref_name }}" -eq "main") {
            $title = "Gooey $version"
            gh release delete $version -y
            gh release create $version $exe --notes-file $changes -t $title
          }
          if ("${{ github.ref_name }}" -eq "dev") {
            $title = "Gooey Nightly"
            gh release delete nightly -y
            gh release create nightly $exe --notes-file $changes -t $title --prerelease
          }
