name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 5
      - uses: actions/cache@v3
        id: library-cache
        with:
          path: |
            build/libs
            build/_deps
          key: library-cache-${{ hashFiles('**/CMakeLists.txt') }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $vswhere = "${Env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $vspath = & $vswhere -products * -latest -property installationPath
          & "$vspath\Common7\Tools\Launch-VsDevShell.ps1" -HostArch amd64 -Arch amd64 -SkipAutomaticLocation
          cmake --preset Release
          cmake --build --preset Release
          
          $version = Get-Content "build/version.txt"

          git --no-pager log -5 --oneline --no-decorate > build/changes.txt
          $changes = Get-Item "build/changes.txt"

          7z a build/Airglow.zip build/Airglow.exe

          $exe = Get-Item "build/Airglow.exe"
          $zip = Get-Item "build/Airglow.zip"

          if ("${{ github.ref_name }}" -eq "main") {
            $title = "Airglow $version"
            gh release delete $version -y
            gh release create $version $zip --notes-file $changes -t $title
          }

          if ("${{ github.ref_name }}" -eq "dev") {
            $title = "Airglow Nightly"
            gh release delete nightly -y
            gh release create nightly $zip --notes-file $changes -t $title --prerelease
          }
