name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "dev"

permissions:
  contents: write

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Cache
        id: nuget-cache
        uses: actions/cache@v3
        with:
          path: external
          key: nuget-cache-${{ hashFiles('**/CMakeLists.txt') }}
      - name: Restore nuget
        if: steps.nuget-cache.outputs.cache-hit != 'true'
        run: |
          nuget install Microsoft.Web.WebView2 -OutputDirectory external
          nuget install Microsoft.Windows.ImplementationLibrary -OutputDirectory external
      - name: Build
        run: |
          cmake --preset Release
          cmake --build --preset Release
          git --no-pager log -5 --oneline --no-decorate >> build/Release/notes.md
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $exe = Get-Item "build/Release/Gooey.exe"
          $version = Get-Item "build/notes.md"
          $notes = Get-Item "build/Release/notes.md"
          if ("${{ github.ref_name }}" -eq "main") {$title = "Gooey " + $version; $tag = $version}
          if ("${{ github.ref_name }}" -eq "dev") {$title = "Development"; $tag = "development"}
          gh release delete $tag -y
          gh release create $tag $path -F $notes -t $title
