name: Airglow

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "*"
          check-latest: true
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml

      - name: Install node_modules
        run: |
          pnpm install --frozen-lockfile

      - name: Cache
        uses: actions/cache@v4
        id: deps
        with:
          path: |
            build/_deps
          key: deps-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Stable release
        if: github.ref == 'refs/heads/main'
        run: |
          Import-Module ${{ github.workspace }}\tools\PowerShell
          Invoke-UnityBuild
          Invoke-Archive
          Invoke-StableRelease
