name: Gooey Release

on:
  workflow_dispatch:
  # push:
  #   branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: nuget-cache
        with:
          path: external
          key: nuget-cache-${{ hashFiles('**/CMakeLists.txt') }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $vswhere = "${Env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $vspath = & $vswhere -products * -latest -property installationPath
          & "$vspath\Common7\Tools\Launch-VsDevShell.ps1" -HostArch amd64 -Arch amd64 -SkipAutomaticLocation
          cmake --preset Release
          cmake --build --preset Release
          git --no-pager log -5 --oneline --no-decorate > build/changes.txt

          $version = Get-Content "build/version.txt"
          $changes = Get-Item "build/changes.txt"
          $exe = Get-Item "build/Gooey.exe"

          if ("${{ github.ref_name }}" -eq "main") {
            $title = "Gooey $version"
            gh release delete $version -y
            gh release create $version $exe --notes-file $changes -t $title
          }

          if ("${{ github.ref_name }}" -eq "dev") {
            $title = "Gooey Nightly"
            gh release delete nightly -y
            gh release create nightly $exe --notes-file $changes -t $title --prerelease
          }
