name: Build

on:
  push:
    branches:
      - "main"
      - "dev"
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: pwsh

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore nuget
        if: steps.nuget-cache.outputs.cache-hit != 'true'
        run: .\scripts\packages.ps1

      - name: Cache
        id: nuget-cache
        uses: actions/cache@v3
        with:
          path: packages
          key: ${{ runner.os }}-${{ matrix.node-version }}-nuget-cache-${{ hashFiles('**/CMakeLists.txt') }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if ("${{ github.ref_name }}" -eq "main") {$title = "Stable"; $tag = "stable"}
          if ("${{ github.ref_name }}" -eq "dev") {$title = "Development"; $tag = "development"}
          .\scripts\gh_release.ps1
          $path = Get-Item ".\build\Release\Gooey.exe"
          $notes = Get-Item ".\notes.md"
          gh release delete $tag -y
          gh release create $tag $path -F $notes -t $title
