name: Release

on:
  workflow_dispatch:
  push:
    branches: [main, dev]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 5
      - uses: actions/cache@v3
        id: library-cache
        with:
          path: build/_deps
          key: library-cache-${{ hashFiles('**/CMakeLists.txt') }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $vswhere = "${Env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $vspath = & $vswhere -products * -latest -property installationPath
          & "$vspath\Common7\Tools\Launch-VsDevShell.ps1" -HostArch amd64 -Arch amd64 -SkipAutomaticLocation
          cmake --preset release
          cmake --build --preset release

          7z a build/Airglow.zip build/Airglow.exe

          $exe = Get-Item "build/Airglow.exe"
          $zip = Get-Item "build/Airglow.zip"

          $name = (Get-Content Airglow.json | ConvertFrom-Json).name
          $version = (Get-Content Airglow.json | ConvertFrom-Json).version
          $changes = git --no-pager log -5 --oneline --no-decorate

          if ("${{ github.ref_name }}" -eq "main") {
            $title = "$name $version"
            gh release delete $version -y
            gh release create $version $exe $zip --notes-file $changes -t $title
          }

          if ("${{ github.ref_name }}" -eq "dev") {
            $title = "$name Nightly"
            gh release delete nightly -y
            gh release create nightly $exe $zip --notes-file $changes -t $title --prerelease
          }
