name: Release

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 5
          submodules: true
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          node-version: "*"
          check-latest: true
          cache: "pnpm"
          cache-dependency-path: gui/pnpm-lock.yaml
      - run: |
          Push-Location
          Set-Location gui
          pnpm install --frozen-lockfile
          Pop-Location
      - uses: actions/cache@v3
        id: library-cache
        with:
          path: |
            build/_deps
            build/libs/Nuget
          key: library-cache-${{ hashFiles('**/CMakeLists.txt') }}
      - run: |
          $vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $vspath = & $vswhere -products * -latest -property installationPath
          & "$vspath\Common7\Tools\Launch-VsDevShell.ps1" -HostArch amd64 -Arch amd64 -SkipAutomaticLocation

          cmake -B build -S . -G "Ninja" -DCMAKE_BUILD_TYPE=Release
          cmake --build build

          Push-Location
          Set-Location build/Airglow
          7z a Airglow.zip Airglow.exe Microsoft.Web.WebView2.Core.dll gui
          Pop-Location

          $zip = Get-Item "build/Airglow/Airglow.zip"
          $version = Get-Content "build/version.txt"
          $notes = Get-Item "build/release_notes.txt"
          $commit = git rev-parse --short HEAD

          if ("${{ github.ref_name }}" -eq "main") {
            gh release delete $version -y
            gh release create $version $zip -F $notes -t "Airglow $version"
          }

          if ("${{ github.ref_name }}" -eq "dev") {
            gh release delete $version -y
            gh release create $version $zip -F $notes -t "Airglow Nightly ($commit)" -p
          }
