name: Release

on:
  workflow_dispatch:
  push:
    branches: [main, dev]

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 5
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - uses: actions/setup-node@v3
        with:
          node-version: "*"
          check-latest: true
          cache: "pnpm"
          cache-dependency-path: gui/pnpm-lock.yaml
      - run: |
          Push-Location
          Set-Location gui
          pnpm install --frozen-lockfile
          Pop-Location
      - uses: actions/cache@v3
        id: library-cache
        with:
          path: build/_deps
          key: library-cache-${{ hashFiles('**/CMakeLists.txt') }}
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          $vswhere = "${Env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $vspath = & $vswhere -products * -latest -property installationPath
          & "$vspath\Common7\Tools\Launch-VsDevShell.ps1" -HostArch amd64 -Arch amd64 -SkipAutomaticLocation
          cmake --preset release
          cmake --build --preset release

          $zip = Get-Item "build/Airglow.zip"
          git --no-pager log -5 --oneline --no-decorate > build/notes.txt

          $name = (Get-Content Airglow.json | ConvertFrom-Json).name
          $version = (Get-Content Airglow.json | ConvertFrom-Json).version
          $notes = Get-Item "build/notes.txt"

          if ("${{ github.ref_name }}" -eq "main") {
            $title = "$name $version"
            gh release delete $version -y
            gh release create $version $zip -F $notes -t $title
          }

          if ("${{ github.ref_name }}" -eq "dev") {
            $title = "$name Nightly"
            gh release delete nightly -y
            gh release create nightly $zip -F $notes -t $title -p
          }
